# Purpose: Define a custom image for DB

# Using the official image is standard practice as it handles all the complex setup
# (like running the database process and volume configuration) internally.
# We choose the 'alpine' version for a smaller image size.
FROM postgres:16-alpine